/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import weka.core.Instances;


/**
 *
 * @author Edgar
 */
public class RegresionLineal extends javax.swing.JFrame {
    //Declarar la logica
    Logica L = new Logica();
    
    
    /**
     * Creates new form RegresionLineal
     */
    public RegresionLineal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JLabel();
        T2 = new javax.swing.JLabel();
        Separador3 = new javax.swing.JSeparator();
        Ecuacion = new javax.swing.JTextField();
        T3 = new javax.swing.JLabel();
        Opciones = new javax.swing.JComboBox<>();
        ObtenerDatos = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        T4 = new javax.swing.JLabel();
        VariableX1 = new javax.swing.JTextField();
        T5 = new javax.swing.JLabel();
        ObtenerPronostico = new javax.swing.JButton();
        TextoPronostico1 = new javax.swing.JLabel();
        VariableX2 = new javax.swing.JTextField();
        TextoPronostico2 = new javax.swing.JLabel();
        VariableY = new javax.swing.JTextField();
        Opcion = new javax.swing.JLabel();
        Separador2 = new javax.swing.JSeparator();
        Separador1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        T1.setText("Seleccione los datos que desea obtener:");

        T2.setText("Ecuacion resultante:");

        Ecuacion.setEditable(false);
        Ecuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcuacionActionPerformed(evt);
            }
        });

        T3.setText("Grafica resultante:");

        Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dias-Casos", "Dias-Muertes" }));
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });

        ObtenerDatos.setText("Obtener datos");
        ObtenerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtenerDatosActionPerformed(evt);
            }
        });

        Panel.setEnabled(false);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        T4.setText("Pronostico:");

        T5.setText("Dia de pronostico:");

        ObtenerPronostico.setText("Obtener pronostico");
        ObtenerPronostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtenerPronosticoActionPerformed(evt);
            }
        });

        TextoPronostico1.setText("Para el dia #");

        VariableX2.setEditable(false);

        TextoPronostico2.setText("se estiman un total de");

        VariableY.setEditable(false);

        Opcion.setText("casos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separador3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separador2)
                            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(T2)
                                    .addComponent(T4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(T5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(VariableX1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ObtenerPronostico))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoPronostico1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(VariableX2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoPronostico2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(VariableY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Opcion))
                                    .addComponent(T3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(T1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ecuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ObtenerDatos))
                                    .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1)
                    .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ecuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ObtenerDatos))
                .addGap(14, 14, 14)
                .addComponent(Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VariableX1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(T5)
                        .addComponent(ObtenerPronostico)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoPronostico1)
                    .addComponent(VariableX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoPronostico2)
                    .addComponent(VariableY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opcion))
                .addGap(18, 18, 18)
                .addComponent(Separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T3)
                .addGap(18, 18, 18)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EcuacionActionPerformed

    private void ObtenerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtenerDatosActionPerformed
        int o = 0;
        Instances Datos = null;
        String N = null, E = null;
        
        if(Opciones.getSelectedItem().equals("Dias-Casos")){
            o=1;
            N="Casos";
            E="Escala dias-casos";
        }else if(Opciones.getSelectedItem().equals("Dias-Muertes")){
            o=2;
            N="Muertes";
            E="Escala dias-muertes";
        }
        
        try {
            Datos = L.ObtenerDS("COVID19.csv", o, "DS");
        } catch (Exception ex) {
            Logger.getLogger(RegresionLineal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Ecuacion.setText((String) L.RegresionLineal(o).get(0));
        } catch (Exception ex) {
            Logger.getLogger(RegresionLineal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        XYSeries Serie = new XYSeries(E);
        for(int x=0;x<Datos.size();x++){
            Serie.add(Datos.get(x).value(0), Datos.get(x).value(1));
        }
        
        XYSeriesCollection Coleccion = new XYSeriesCollection();
        Coleccion.addSeries(Serie);
        
        JFreeChart Grafico = ChartFactory.createXYLineChart("Dias-"+N, "Dias", N, Coleccion,PlotOrientation.VERTICAL,true, false, false);
        ChartPanel PanelGrafico = new ChartPanel(Grafico);
        Panel.setLayout(new java.awt.BorderLayout());
        Panel.add(PanelGrafico);
        Panel.validate();
    }//GEN-LAST:event_ObtenerDatosActionPerformed

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        if(Opciones.getSelectedItem().equals("Dias-Casos")){
            Opcion.setText("casos");
        }else if(Opciones.getSelectedItem().equals("Dias-Muertes")){
            Opcion.setText("muertes");
        }
    }//GEN-LAST:event_OpcionesActionPerformed

    private void ObtenerPronosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtenerPronosticoActionPerformed
        int o=0;
        double Y = 0, M = 0, X = 0, B = 0;
        ArrayList <Object> R = new ArrayList<>();
        
        if(Opciones.getSelectedItem().equals("Dias-Casos")){
            o=1;
        }else if(Opciones.getSelectedItem().equals("Dias-Muertes")){
            o=2;
        }
                
        VariableX2.setText(VariableX1.getText());
        try {
            R = L.RegresionLineal(o);
        } catch (Exception ex) {
            Logger.getLogger(RegresionLineal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        M = (double) R.get(1);
        X = Double.parseDouble(VariableX1.getText());
        B = (double) R.get(2);
        Y=M*X+B;
        if(Y<0){
        Y=0;
        }
        VariableY.setText(String.valueOf(Y));
    }//GEN-LAST:event_ObtenerPronosticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegresionLineal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(RegresionLineal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ecuacion;
    private javax.swing.JButton ObtenerDatos;
    private javax.swing.JButton ObtenerPronostico;
    private javax.swing.JLabel Opcion;
    private javax.swing.JComboBox<String> Opciones;
    private javax.swing.JPanel Panel;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator Separador3;
    private javax.swing.JLabel T1;
    private javax.swing.JLabel T2;
    private javax.swing.JLabel T3;
    private javax.swing.JLabel T4;
    private javax.swing.JLabel T5;
    private javax.swing.JLabel TextoPronostico1;
    private javax.swing.JLabel TextoPronostico2;
    private javax.swing.JTextField VariableX1;
    private javax.swing.JTextField VariableX2;
    private javax.swing.JTextField VariableY;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
